name: 'Safer Runner Action'
description: 'Multi-layer security and reporting for GitHub Actions'
author: 'PortSwigger'
branding:
  icon: 'shield'
  color: 'red'

inputs:
  mode:
    description: 'Operation mode: "analyze" to log traffic without blocking, "enforce" to block unauthorized domains'
    required: false
    default: 'analyze'
  allowed-domains:
    description: 'Space-separated list of additional domains to allow (beyond GitHub required domains)'
    required: false
    default: ''
  primary-dns-server:
    description: 'Primary DNS server for allowed domains (defaults to Quad9: 9.9.9.9)'
    required: false
    default: '9.9.9.9'
  secondary-dns-server:
    description: 'Secondary DNS server for redundancy (defaults to Quad9 secondary: 149.112.112.112)'
    required: false
    default: '149.112.112.112'
  fail-on-tampering:
    description: 'Whether to fail the workflow after job completion if security configuration tampering is detected'
    required: false
    default: 'false'
  block-risky-github-subdomains:
    description: 'Whether to block risky GitHub subdomains (gist.github.com, gist.githubusercontent.com, raw.githubusercontent.com) in enforce mode. Set to "false" if you need these domains.'
    required: false
    default: 'true'
  disable-sudo:
    description: 'Whether to disable sudo access for the runner user after setup is complete. This prevents malicious code from using sudo to bypass security controls.'
    required: false
    default: 'false'
  sudo-config:
    description: 'Custom sudoers configuration for the runner user (only used when disable-sudo is false). Provide sudoers rules as a multi-line string.'
    required: false
    default: ''
  disable-docker:
    description: 'Whether to remove runner user from docker group. This prevents container usage, blocking container escape attacks and docker socket abuse.'
    required: false
    default: 'false'
  stop-docker:
    description: 'Whether to completely stop and disable the Docker service. This provides stronger protection than disable-docker by preventing all Docker usage system-wide.'
    required: false
    default: 'false'

runs:
  using: 'node20'
  pre: 'dist/pre/index.js'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
