name: 'Safer Runner Action'
description: 'Add network security layer with DNS filtering and iptables rules to prevent communication with malicious domains'
author: 'PortSwigger'
branding:
  icon: 'shield'
  color: 'red'

inputs:
  mode:
    description: 'Operation mode: "analyze" to log traffic without blocking, "enforce" to block unauthorized domains'
    required: false
    default: 'analyze'
  allowed-domains:
    description: 'Space-separated list of additional domains to allow (beyond GitHub required domains)'
    required: false
    default: ''
  fail-on-tampering:
    description: 'Whether to fail the workflow after job completion if security configuration tampering is detected'
    required: false
    default: 'false'
  block-risky-github-subdomains:
    description: 'Whether to block risky GitHub subdomains (gist.github.com, gist.githubusercontent.com, raw.githubusercontent.com) in enforce mode. Set to "false" if you need these domains.'
    required: false
    default: 'true'

runs:
  using: 'node20'
  pre: 'dist/pre.js'
  main: 'dist/main.js'
  post: 'dist/post.js'