name: 'Safer Runner Action'
description: 'Add network security layer with DNS filtering and iptables rules to prevent communication with malicious domains'
author: 'PortSwigger'
branding:
  icon: 'shield'
  color: 'red'

inputs:
  mode:
    description: 'Operation mode: "analyze" to log traffic without blocking, "enforce" to block unauthorized domains'
    required: false
    default: 'analyze'
  allowed-domains:
    description: 'Space-separated list of additional domains to allow (beyond GitHub required domains)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y dnsmasq ipset

    - name: Configure iptables rules
      shell: bash
      run: |
        # Allow established and related connections
        sudo iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
        
        # Allow Azure metadata service (required for GitHub Actions)
        sudo iptables -A OUTPUT -o eth0 -d 168.63.129.16 -j ACCEPT
        sudo iptables -A OUTPUT -o eth0 -d 169.254.169.254 -j ACCEPT
        
        # Allow localhost traffic
        sudo iptables -A OUTPUT -o lo -s 127.0.0.1 -d 127.0.0.1 -j ACCEPT
        
        # Log processing for debugging
        sudo iptables -A OUTPUT -j LOG --log-prefix='Processing: '
        
        # Create ipset for GitHub Actions required domains
        sudo ipset create github hash:ip
        sudo iptables -A OUTPUT -m set --match-set github dst -j LOG --log-prefix='GitHub-Allow: '
        sudo iptables -A OUTPUT -m set --match-set github dst -j ACCEPT
        
        # Create ipset for user allowed domains
        sudo ipset create user hash:ip
        sudo iptables -A OUTPUT -m set --match-set user dst -j LOG --log-prefix='User-Allow: '
        sudo iptables -A OUTPUT -m set --match-set user dst -j ACCEPT

    - name: Configure DNS filtering
      shell: bash
      run: |
        # Configure systemd-resolved to use our DNS server
        sudo mkdir -p /etc/systemd/resolved.conf.d
        sudo tee /etc/systemd/resolved.conf.d/no-stub.conf > /dev/null <<EOF
        [Resolve]
        DNS=127.0.0.1
        DNSSEC=yes
        DNSStubListener=no
        EOF
        
        # Update resolv.conf to use localhost
        sudo unlink /etc/resolv.conf
        sudo tee /etc/resolv.conf > /dev/null <<EOF
        nameserver 127.0.0.1
        EOF

    - name: Configure DNSMasq
      shell: bash
      env:
        MODE: ${{ inputs.mode }}
        ALLOWED_DOMAINS: ${{ inputs.allowed-domains }}
        DNS_SERVER: '9.9.9.9'
      run: |
        # Base dnsmasq configuration
        sudo tee /etc/dnsmasq.conf > /dev/null <<EOF
        # Enable query logging for summary generation
        log-queries=extra
        
        EOF
        
        # Configure DNS policy based on mode
        if [ "$MODE" = "enforce" ]; then
          # NXDOMAIN all unlisted DNS (default deny)
          echo "server=" | sudo tee -a /etc/dnsmasq.conf
        else
          # Analyze mode: allow all DNS queries to go through
          echo "server=$DNS_SERVER" | sudo tee -a /etc/dnsmasq.conf
        fi
        
        # Add configuration for allowed domains
        sudo tee -a /etc/dnsmasq.conf > /dev/null <<EOF
        
        # Required GitHub Actions domains - Essential Operations
        server=/github.com/$DNS_SERVER
        ipset=/github.com/github
        
        server=/actions.githubusercontent.com/$DNS_SERVER  
        ipset=/actions.githubusercontent.com/github
        
        server=/api.github.com/$DNS_SERVER
        ipset=/api.github.com/github
        
        # Downloading Actions
        server=/codeload.github.com/$DNS_SERVER
        ipset=/codeload.github.com/github
        
        server=/pkg.actions.githubusercontent.com/$DNS_SERVER
        ipset=/pkg.actions.githubusercontent.com/github
        
        # Publishing & Container Registry
        server=/ghcr.io/$DNS_SERVER
        ipset=/ghcr.io/github
        
        # Artifact Upload/Download
        server=/results-receiver.actions.githubusercontent.com/$DNS_SERVER
        ipset=/results-receiver.actions.githubusercontent.com/github
        
        # GitHub Actions specific Azure blob storage accounts (from GitHub API)
        server=/productionresultssa0.blob.core.windows.net/$DNS_SERVER
        ipset=/productionresultssa0.blob.core.windows.net/github
        server=/productionresultssa1.blob.core.windows.net/$DNS_SERVER
        ipset=/productionresultssa1.blob.core.windows.net/github
        server=/productionresultssa2.blob.core.windows.net/$DNS_SERVER
        ipset=/productionresultssa2.blob.core.windows.net/github
        server=/productionresultssa3.blob.core.windows.net/$DNS_SERVER
        ipset=/productionresultssa3.blob.core.windows.net/github
        server=/productionresultssa4.blob.core.windows.net/$DNS_SERVER
        ipset=/productionresultssa4.blob.core.windows.net/github
        server=/productionresultssa5.blob.core.windows.net/$DNS_SERVER
        ipset=/productionresultssa5.blob.core.windows.net/github
        server=/productionresultssa6.blob.core.windows.net/$DNS_SERVER
        ipset=/productionresultssa6.blob.core.windows.net/github
        server=/productionresultssa7.blob.core.windows.net/$DNS_SERVER
        ipset=/productionresultssa7.blob.core.windows.net/github
        server=/productionresultssa8.blob.core.windows.net/$DNS_SERVER
        ipset=/productionresultssa8.blob.core.windows.net/github
        server=/productionresultssa9.blob.core.windows.net/$DNS_SERVER
        ipset=/productionresultssa9.blob.core.windows.net/github
        server=/productionresultssa10.blob.core.windows.net/$DNS_SERVER
        ipset=/productionresultssa10.blob.core.windows.net/github
        server=/productionresultssa11.blob.core.windows.net/$DNS_SERVER
        ipset=/productionresultssa11.blob.core.windows.net/github
        server=/productionresultssa12.blob.core.windows.net/$DNS_SERVER
        ipset=/productionresultssa12.blob.core.windows.net/github
        server=/productionresultssa13.blob.core.windows.net/$DNS_SERVER
        ipset=/productionresultssa13.blob.core.windows.net/github
        server=/productionresultssa14.blob.core.windows.net/$DNS_SERVER
        ipset=/productionresultssa14.blob.core.windows.net/github
        server=/productionresultssa15.blob.core.windows.net/$DNS_SERVER
        ipset=/productionresultssa15.blob.core.windows.net/github
        server=/productionresultssa16.blob.core.windows.net/$DNS_SERVER
        ipset=/productionresultssa16.blob.core.windows.net/github
        server=/productionresultssa17.blob.core.windows.net/$DNS_SERVER
        ipset=/productionresultssa17.blob.core.windows.net/github
        server=/productionresultssa18.blob.core.windows.net/$DNS_SERVER
        ipset=/productionresultssa18.blob.core.windows.net/github
        server=/productionresultssa19.blob.core.windows.net/$DNS_SERVER
        ipset=/productionresultssa19.blob.core.windows.net/github
        
        # Runner Version Updates
        server=/objects.githubusercontent.com/$DNS_SERVER
        ipset=/objects.githubusercontent.com/github
        
        server=/objects-origin.githubusercontent.com/$DNS_SERVER
        ipset=/objects-origin.githubusercontent.com/github
        
        server=/github-releases.githubusercontent.com/$DNS_SERVER
        ipset=/github-releases.githubusercontent.com/github
        
        server=/github-registry-files.githubusercontent.com/$DNS_SERVER
        ipset=/github-registry-files.githubusercontent.com/github
        
        # Package Management
        server=/pkg.github.com/$DNS_SERVER
        ipset=/pkg.github.com/github
        
        server=/pkg-containers.githubusercontent.com/$DNS_SERVER
        ipset=/pkg-containers.githubusercontent.com/github
        
        # Git Large File Storage
        server=/github-cloud.githubusercontent.com/$DNS_SERVER
        ipset=/github-cloud.githubusercontent.com/github
        
        server=/github-cloud.s3.amazonaws.com/$DNS_SERVER
        ipset=/github-cloud.s3.amazonaws.com/github
        
        # Additional Required Services
        server=/dependabot-actions.githubapp.com/$DNS_SERVER
        ipset=/dependabot-actions.githubapp.com/github
        
        server=/release-assets.githubusercontent.com/$DNS_SERVER
        ipset=/release-assets.githubusercontent.com/github
        
        server=/api.snapcraft.io/$DNS_SERVER
        ipset=/api.snapcraft.io/github
        EOF
        
        # Add custom allowed domains if provided
        if [ -n "$ALLOWED_DOMAINS" ]; then
          for domain in $ALLOWED_DOMAINS; do
            if [ -n "$domain" ]; then
              echo "server=/$domain/$DNS_SERVER" | sudo tee -a /etc/dnsmasq.conf
              echo "ipset=/$domain/user" | sudo tee -a /etc/dnsmasq.conf
            fi
          done
        fi

    - name: Start services
      shell: bash
      env:
        DNS_SERVER: '9.9.9.9'
      run: |
        # Restart systemd-resolved and start dnsmasq
        sudo systemctl restart systemd-resolved
        sudo systemctl enable dnsmasq
        sudo systemctl start dnsmasq
        
        # Allow DNS traffic to our upstream server
        sudo iptables -A OUTPUT -o eth0 -d "$DNS_SERVER" -p udp --dport 53 -m owner --uid-owner $(id -u dnsmasq) -j ACCEPT

    - name: Finalize security rules
      shell: bash
      env:
        MODE: ${{ inputs.mode }}
      run: |
        if [ "$MODE" = "enforce" ]; then
          # Log dropped packets for debugging
          sudo iptables -A OUTPUT -o eth0 -j LOG --log-prefix='Drop-Enforce: '

          # DEFAULT DENY: Drop external traffic not explicitly allowed (scoped to eth0)
          sudo iptables -A OUTPUT -o eth0 -j DROP
        else

          # Log other traffic for analysis but allow it
          sudo iptables -A OUTPUT -j LOG --log-prefix='Allow-Analyze: '
          sudo iptables -A OUTPUT -j ACCEPT
        fi

    - name: Generate Network Access Summary
      shell: bash
      run: |
        echo "## Network Access Provenance" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Domain/IP | Port | Status |" >> $GITHUB_STEP_SUMMARY
        echo "|-----------|------|--------|" >> $GITHUB_STEP_SUMMARY

        # Parse GitHub allowed connections
        sudo grep "GitHub-Allow: " /var/log/syslog 2>/dev/null | while read -r line; do
          if [[ $line =~ DST=([0-9.]+) ]]; then
            ip="${BASH_REMATCH[1]}"
            port="443"
            if [[ $line =~ DPT=([0-9]+) ]]; then
              port="${BASH_REMATCH[1]}"
            fi
            echo "| $ip | $port | ALLOWED |" >> $GITHUB_STEP_SUMMARY
          fi
        done

        # Parse user allowed connections
        sudo grep "User-Allow: " /var/log/syslog 2>/dev/null | while read -r line; do
          if [[ $line =~ DST=([0-9.]+) ]]; then
            ip="${BASH_REMATCH[1]}"
            port="443"
            if [[ $line =~ DPT=([0-9]+) ]]; then
              port="${BASH_REMATCH[1]}"
            fi
            echo "| $ip | $port | ALLOWED |" >> $GITHUB_STEP_SUMMARY
          fi
        done

        # Parse blocked connections
        sudo grep "Drop-Enforce: " /var/log/syslog 2>/dev/null | while read -r line; do
          if [[ $line =~ DST=([0-9.]+) ]]; then
            ip="${BASH_REMATCH[1]}"
            port="443"
            if [[ $line =~ DPT=([0-9]+) ]]; then
              port="${BASH_REMATCH[1]}"
            fi
            echo "| $ip | $port | DENIED |" >> $GITHUB_STEP_SUMMARY
          fi
        done