name: 'Safer Runner Action'
description: 'Add network security layer with DNS filtering and iptables rules to prevent communication with malicious domains'
author: 'PortSwigger'
branding:
  icon: 'shield'
  color: 'red'

inputs:
  mode:
    description: 'Operation mode: "analyze" to log traffic without blocking, "enforce" to block unauthorized domains'
    required: false
    default: 'analyze'
  allowed-domains:
    description: 'Space-separated list of additional domains to allow (beyond GitHub required domains)'
    required: false
    default: ''
  fail-on-tampering:
    description: 'Whether to fail the workflow after job completion if security configuration tampering is detected'
    required: false
    default: 'false'
  block-risky-github-subdomains:
    description: 'Whether to block risky GitHub subdomains (gist.github.com, gist.githubusercontent.com, raw.githubusercontent.com) in enforce mode. Set to "false" if you need these domains.'
    required: false
    default: 'true'
  disable-sudo:
    description: 'Whether to disable sudo access for the runner user after setup is complete. This prevents malicious code from using sudo to bypass security controls.'
    required: false
    default: 'false'
  sudo-config:
    description: 'Custom sudoers configuration for the runner user (only used when disable-sudo is false). Provide sudoers rules as a multi-line string.'
    required: false
    default: ''

runs:
  using: 'node20'
  pre: 'dist/pre/index.js'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'