on:
  workflow_dispatch: {}

jobs:
  secure-runner:
    runs-on: ubuntu-latest
    steps:
    - run: |
        sudo apt-get update
        sudo apt-get install snort -y
        sudo cat /etc/snort/snort.conf
