on:
  workflow_dispatch: {}

jobs:
  iptables:
    runs-on: ubuntu-latest
    steps:
    - run: |
        sudo iptables -A OUTPUT -m state --state NEW -j LOG --log-prefix='iptables_output'
    - run: |
        ssh git@github.com || true
        curl https://github.com
        dig portswigger.net
    - run: |
        grep iptables_output /var/log/syslog
  dnsmasq:
    runs-on: ubuntu-latest
    steps:
    - run: |
        sudo apt-get install dnsmasq -y
        sudo systemctl disable systemd-resolved
        sudo systemctl stop systemd-resolved

        sudo unlink /etc/resolv.conf
        sudo tee /etc/resolv.conf > /dev/null <<EOF
        nameserver 1.1.1.3
        nameserver 1.0.0.3
        EOF

        sudo systemctl enable dnsmasq
        sudo systemctl start dnsmasq
        sudo cat /etc/dnsmasq.conf

    - run: |
        ssh git@github.com || true
        curl https://github.com
        dig portswigger.net
    - run: |
        true
